---
#
# {{ ansible_managed }}
#
{% set url = wsgi_base_url + "/" + service.name %}
{% set inventory= "/home/" + wsgi_user + "/ansible-ws/tests/data/inventories" %}
parameters:
  group:
    desc: "The name of the group"
    attributes:
      - required
  key:
    desc: "The key to get"
    attributes:
      - required
  inventory:
    desc: "The folder or inventory file to used to find groups_vars"
    default: "{{ inventory }}"
examples:
  - desc: "To have help"
    url: "{{ url }}"
  - desc: "To get value of var countries.dict from group database_app1_prod"
    url: "{{ url }}?group=database_app1_prod&key=countries.dict&inventory={{ inventory }}"
  - desc: "To get value of var countries.dict from group database_app1_prod"
    url: "{{ url }}?group=database_app1_prod&key=countries.dict&inventory={{ inventory }}"
...