#
# {{ ansible_managed }}
#
{% set playbook = "/home/" + wsgi_user + "/ansible-ws/tests/data/playbooks/tags.yml" %}
---
cache:
  resource: playbook
  type: tasks
parameters:
  playbook:
    desc: "The playbook from gather tags"
    attributes:
      - required
  format:
    desc: "The output format of json results"
    choices:
      - "sui"
      - "raw"
    default: "sui"
  cache:
    desc: "To manage cache"
    choices:
      - "use"
      - "pass"
      - "flush"
    default: "use"
examples:
  - desc: "To get tags for playbook {{ playbook }}"
    url: "{{ url }}?playbook={{ playbook }}"
...