#
# {{ ansible_managed }}
#
{% set url = wsgi_base_url + "/" + service.name %}
---
parameters:
  action:
    desc: ""
    choices:
      - add
      - info
    default: "info"
  private_key:
    desc: "The ssh private key to use"
    default: "/home/{{ wsgi_user }}/ansible-ws/tests/data/agent/ansible-ws"
  passphrase:
    desc: "The passphrase of the private key"
examples:
  - desc: "To get information about agent"
    url: "{{ url }}"
...