---
- name: Ubuntu configuration
  become: true
  become_user: root
  block:

    - name: Install dependencies
      apt:
        name:
          - apache2
          - libapache2-mod-wsgi-py3
          - python3-psutil
          - python3-pexpect
        state: latest

    - name: Deploy apache configuration
      template:
        src: httpd.conf
        dest: /etc/apache2/conf-available/{{ git_name }}.conf

    - name: Enable apache configuration
      shell: a2enconf {{ git_name }}.conf

    - name: Reload apache configuration
      systemd:
        name: apache2
        state: reloaded
        enabled: yes
...