---
git_name: ansible-ws
git_repo: "https://github.com/vengaar/{{ git_name }}.git"
git_clone: false
git_version: HEAD
wsgi_logfile: /home/{{ wsgi_user }}/{{ git_name }}.log
wsgi_user: "{{ git_name }}"
wsgi_port: 80
wsgi_base_url: http://{{ ansible_default_ipv4.address }}:{{ wsgi_port }}
wsgi_services:
  - name: ansible_hosts
  - name: playbook_tags
  - name: playbook_tasks
  - name: playbook_launch
  - name: playbook_run
#   - name: inventory_grapher
  - name: groupvars
  - name: ssh_agent
grapher_dir: "/home/{{ wsgi_user }}/grapher_output"
runs_dir: "/home/{{ wsgi_user }}/wapi_runs"
selinux:
  files:
    - "{{ wsgi_logfile }}"
    - "/home/{{ wsgi_user }}/.ansible/tmp(/.*)?"
...