---
git_name: ansible-ws
git_repo: "https://github.com/vengaar/{{ git_name }}.git"
git_clone: false
git_version: HEAD
wsgi_logfile: /home/{{ wsgi_user }}/{{ git_name }}.log
wsgi_user: "{{ git_name }}"
wsgi_port: 8044
wsgi_base_url: http://{{ ansible_default_ipv4.address }}:{{ wsgi_port }}
wsgi_services:
  - name: sw2
    alias: sw2/query
working_dir: "/home/{{ wsgi_user }}/{{ git_name }}@working"
runs_dir: "{{ working_dir }}/runs"
graph_dir: "{{ working_dir }}/graphs"
selinux:
  files:
    - "{{ wsgi_logfile }}"
    - "/home/{{ wsgi_user }}/.ansible/tmp(/.*)?"
os_version: "{{ ansible_distribution }}/{{ ansible_distribution_major_version }}"
required:
  os:
    - "Fedora/28"
    - "Fedora/29"
    - "Ubuntu/18"
...