---
#
# {{ ansible_managed }}
#

ansible:
  runs_dir: "{{ working_dirs.runs }}" 

log:
  config: "/etc/{{ git_name }}/logging.conf"

cache:
  prefix: "/tmp/.sw2.cache."
  ttl: 60

agent:
  path: "{{ working_dirs.agents }}"
  id: "{{ git_name }}"

grapher:
  output: "{{ working_dirs.graphs }}"
  format: png

unittest:
  unittest:
    unittest: unittest
...